In [81]:
import pandas as pd

In [82]:
df = pd.read_csv("superhero_powers.csv")

In [83]:
df.head()

,hero_names,Agility,Accelerated Healing,Lantern Power Ring,Dimensional Awareness,Cold Resistance,Durability,Stealth,Energy Absorption,Flight,...,Web Creation,Reality Warping,Odin Force,Symbiote Costume,Speed Force,Phoenix Force,Molecular Dissipation,Vision - Cryo,Omnipresent,Omniscient
0,3-D Man,True,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
1,A-Bomb,False,True,False,False,False,True,False,False,False,...,False,False,False,False,False,False,False,False,False,False
2,Abe Sapien,True,True,False,False,True,True,False,False,False,...,False,False,False,False,False,False,False,False,False,False
3,Abin Sur,False,False,True,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
4,Abomination,False,True,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False

In [84]:
hero_powers = pd.read_csv("superhero_powers.csv")
hero_powers

,hero_names,Agility,Accelerated Healing,Lantern Power Ring,Dimensional Awareness,Cold Resistance,Durability,Stealth,Energy Absorption,Flight,...,Web Creation,Reality Warping,Odin Force,Symbiote Costume,Speed Force,Phoenix Force,Molecular Dissipation,Vision - Cryo,Omnipresent,Omniscient
0,3-D Man,True,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
1,A-Bomb,False,True,False,False,False,True,False,False,False,...,False,False,False,False,False,False,False,False,False,False
2,Abe Sapien,True,True,False,False,True,True,False,False,False,...,False,False,False,False,False,False,False,False,False,False
3,Abin Sur,False,False,True,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
4,Abomination,False,True,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
662,Yellowjacket II,False,False,False,False,False,False,False,False,True,...,False,False,False,False,False,False,False,False,False,False
663,Ymir,False,False,False,False,True,True,False,False,False,...,False,False,False,False,False,False,False,False,False,False
664,Yoda,True,False,False,False,False,False,True,False,False,...,False,False,False,False,False,False,False,False,False,False
665,Zatanna,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
666,Zoom,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False

In [85]:
hero_dc = pd.read_excel("superhero_info.xlsx", sheet_name = "DC Comics")
hero_marvel = pd.read_excel("superhero_info.xlsx", sheet_name = "Marvel Comics")

In [86]:
hero_dc.to_csv("hero_dc.csv",index = False)

In [87]:
hero_dc.to_pickle("hero.dc.pkl")

In [88]:
hero_dc_pkl = pd.read_pickle("hero.dc.pkl")

In [89]:
hero_dc_csv = pd.read_csv("hero_dc.csv")

In [90]:
hero_dc_csv.info()

<class 'pandas.DataFrame'>
RangeIndex: 215 entries, 0 to 214
Data columns (total 9 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   name        215 non-null    str
 1   Gender      215 non-null    str
 2   Eye color   215 non-null    str
 3   Race        215 non-null    str
 4   Hair color  215 non-null    str
 5   Height      215 non-null    int64
 6   Publisher   215 non-null    str
 7   Alignment   215 non-null    str
 8   Weight      144 non-null    float64
dtypes: float64(1), int64(1), str(7)
memory usage: 15.2 KB

In [78]:
hero_dtype={'name':'string','Gender':'category','Eye color':'string','Race':'string','Hair color':'string','Publisher':'string','Alignment':'category'}

In [ ]:
hero_dc_pkl.info()

<class 'pandas.DataFrame'>
RangeIndex: 215 entries, 0 to 214
Data columns (total 9 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   name        215 non-null    str
 1   Gender      215 non-null    str
 2   Eye color   215 non-null    str
 3   Race        215 non-null    str
 4   Hair color  215 non-null    str
 5   Height      215 non-null    int64
 6   Publisher   215 non-null    str
 7   Alignment   215 non-null    str
 8   Weight      144 non-null    float64
dtypes: float64(1), int64(1), str(7)
memory usage: 15.2 KB